/* ------------------------------------   */
/* This is a test for the sarag package   */
/* which is used in                       */
/* "Algorithms in Real Algebraic Geometry */
/* by S. Basu, R. Pollack, M.-F. Roy      */


/* -------------------------------------- */
/* Chapter                              9 */


/* -------------------------------------- */
/* Chapter                             10 */


(kill(all), load(sarag),0);
0$

deCasteljauIsolateRoots(
expand(
9*x^13-18*x^11-33*x^10+102*x^8
+7*x^7-36*x^6-122*x^5+49*x^4+93*x^3-42*x^2-18*x+9)*
(x+1)*(x^2+1)
,x);
[[- 2, - 1], [- 1], [- 1, 0],
[1/2,5/8],[5/8,3/4],
[1], [1, 2]];



smartSignDetermination(
 [x,x+1,x-2,x-5,x+6,x^2-1],
expand((x^5-9*x^3-x^2+9)*(x^2+1)*(x-7)*(x^2-2*x+1)),
 sSubResTarskiQuery,x);
[[1, 1, 1, 1, 1, 1], 
[1, 1, 1, - 1, 1, 1], 
[1, 1, - 1, - 1, 1, 0], 
[- 1, - 1, - 1, - 1, 1, 1]];

thomEncoding(
expand(
(9*x^13-18*x^11-33*x^10+102*x^8+7*x^7
-36*x^6-122*x^5+49*x^4+93*x^3-42*x^2
-18*x+9)*
(x+1)*(x^2+1))
,x);
[[- 1, 1, - 1, 1, - 1, 1, - 1, 1, - 1, 1, - 1, 1, - 1, 1, - 1, 1], 
[1, - 1, 1, - 1, 1, 1, - 1, 1, - 1, 1, - 1, 1, - 1, 1, - 1, 1], 
[0, 1, - 1, - 1, 1, - 1, 1, - 1, - 1, 1, - 1, 1, - 1, 1, - 1, 1], 
[- 1, 1, - 1, - 1, 1, 1, - 1, - 1, - 1, 1, 1, 1, 1, 1, 1, 1], 
[0, - 1, - 1, 1, 1, - 1, - 1, - 1, 1, 1, 1, 1, 1, 1, 1, 1], 
[1, 1, - 1, - 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]];

/* -------------------------------------- */
/* Chapter                             11 */

archimedianTopology((x^2+y^2-1)*(x-y+1),deCasteljauIsolateRoots,x,y);
[0, [1, [1, 1], 3, [2, 2], 3, [2, 1], 1]];

archimedianTopology(2*y^3+(3*x-3)*y^2+(3*x^2-3*x)*y+x^3,
deCasteljauIsolateRoots,x,y);
[0, [1, [2, 2], 3, [2, 1], 3, [2, 2], 1]];

archimedianTopology(y^5+(-x-1)*y^4+(-2*x+1)*y^3+(2*x+1)*y^2+(2*x-1)*y-x-1,
deCasteljauIsolateRoots,x,y);
[0, [5, [4, 1], 3, [2, 1], 1, [2, 2], 
3, [2, 1], 3, [4, 1], 5]];

archimedianTopology(y^4-6*x*y^2+x^2-4*x^2*y^2+24*x^3,
deCasteljauIsolateRoots,x,y);
[1, [2, [3, 2], 4, [3, 2], 4, [3, 2], 2, [3, 2], 4]];

archimedianTopology(x^4+2*x^2*y^2-x^2+y^4-4*y^2,
deCasteljauIsolateRoots,x,y);
[1, [0, [1, 1], 2, [3, 2], 2, [1, 1], 0]];

archimedianTopology(x^5-x^2*y^3+x*y^4-x^4+x*y^3-y^4+x^3+x^2*y+
x*y^2-2*x^2-y^2+x,
deCasteljauIsolateRoots,x,y);
[1, [1, [2, 1], 3, [2, 2], 1, [2, 2], 3, [2, 1], 1]];

archimedianTopology(diff(16*y^4-4*x^2*y^3-128*y^2+144*x^2*y-27*x^4+256,y),
deCasteljauIsolateRoots,x,y);
[0, [3, [2, 2], 1, [2, 2], 3, [2, 2], 1, [2, 2], 3]];

archimedianTopology(2*x^4-3*x^2*y+y^2-2*y^3+y^4,
deCasteljauIsolateRoots,x,y);
[1, [0, [1, 1], 2, [3, 3], 4, [3, 2], 4, [3, 1], 4, 
[3, 2], 2, [1, 1], 0]];

archimedianTopology(x^4+x^2*y^2-2*x^2*y-x*y^2+y^2,
deCasteljauIsolateRoots,x,y);
[1, [0, [1, 1], 2, [3, 1], 4, [3, 2], 2, [1, 1], 0]];

archimedianTopology( expand((x^2+y^2-1)*(x^2-y^2) + x*y),
deCasteljauIsolateRoots,x,y);
[0, [2, [3, 3], 4, [3, 2], 4, [3, 1], 2]];

archimedianTopology( expand((13*y^2 + 8*x*y + 4*y^2 - 8*x - 8*y + 2)*
(y^2 + x*y - y - 1/6)),
deCasteljauIsolateRoots,x,y);
[0, [4, [3, 2], 2, [3, 2], 4, [3, 1], 4, [3, 3], 4, [3, 1], 4]];

archimedianTopology(x^5 - 5/4*x^3 + 5/16*x - 1/4*y^3 + 3/16*y,
deCasteljauIsolateRoots,x,y);
[0, [1, [2, 2], 3, [2, 1], 3, [2, 2], 3, [2, 1], 3, 
[2, 2], 3, [2, 1], 1]];

archimedianTopology(15/4 + 8*x - 16*x^2 + 8*y - 112*x*y + 128*x^2*y 
- 16*y^2 +128*x*y^2 - 128*x^2*y^2,
deCasteljauIsolateRoots,x,y);
[1, [4, [3, 2], 2, [3, 2], 4, [3, 2], 2, [3, 2], 4]];


archimedianTopology( 55/256 - x + 2*x^2 - 2*x^3 + x^4 - 55/64*y + 
2*x*y - 2*x^2*y +119/64*y^2 - 2*x*y^2 + 
2*x^2*y^2 - 2*y^3 + y^4 ,
deCasteljauIsolateRoots,x,y);
[1, [0, [1, 1], 2, [3, 1], 4, [3, 2], 4, [3, 3], 2, [1, 1], 0]];

