# Spanish xmaxima translation by Juan Pablo Romero Bernal
### $Id: es.msg,v 1.4 2006-12-05 04:21:15 villate Exp $

### Menu.tcl
mcset es "Edit" "Editar"
mcset es "Save to a file" "Guardar a un archivo"
mcset es "Error writing to file" "Error al escribir en el archivo"
mcset es "Batch File" "Ejecutar archivo batch"
mcset es "Open a file to Batch" "Abrir archivo batch"
mcset es "Error writing to file:\n%s" "Error al escribir en el archivo:\n%s" 
mcset es "File" "Archivo"
mcset es "Batch File Silently" "Ejecutar batch en silencio"
mcset es "Open a file to Batch Silently" "Abrir archivo batch silenciosamente"
mcset es "Save Expressions to File" "Guardar expresiones a un archivo"
mcset es "Interrupt" "Interrupción"
mcset es "Restart" "Reiniciar"
mcset es "Input prompt" "Cursor de entrada"
mcset es "Exit" "Salir"
mcset es "Edit" "Editar"
mcset es "Cut" "Cortar"
mcset es "Copy" "Copiar"
mcset es "Paste" "Pegar"
mcset es "Kill" "Eliminar"
mcset es "Yank" "Recuperar"
mcset es "Previous Input" "Entrada previa"
mcset es "Next Input" "Entrada siguiente"
mcset es "Clear input" "Limpiar entrada"
mcset es "Save Console to File" "Guardar la terminal a un archivo"
mcset es "Options" "Opciones"
mcset es "Toggle Browser Visibility" "Alternar la visibilidad del navegador"
mcset es "Plot Windows" "Ventanas de graficación"
mcset es "Embedded" "Embebida"
mcset es "Separate" "Separada"
mcset es "Multiple" "Multiple"
mcset es "Preferences" "Preferencias"
mcset es "Show Tcl Console" "Mostrar consola Tcl"
mcset es "Clear Memory" "Limpiar memoria"
mcset es "Kill All" "Limpiar todo"
mcset es "Kill " "Limpiar "
mcset es "Labels" "Etiquetas"
mcset es "Values" "Valores"
mcset es "Functions" "Funciones"
mcset es "Macros" "Macros"
mcset es "Arrays" "Arreglos"
mcset es "Myoptions" "Myoptions"
mcset es "Props" "Props"
mcset es "Aliases" "Alias"
mcset es "Rules" "Reglas"
mcset es "Gradefs" "Gradefs"
mcset es "Dependencies" "Dependencias"
mcset es "Let_rule_packages" "Let_rule_packages"
mcset es "Run Tests" "Ejecutar tests"
mcset es "Help" "Ayuda"
mcset es "Maxima Manual" "Manual de Maxima"
mcset es "Maxima Manual (xmaxima browser)" "Maxima - manual(navegador Xmaxima)"
mcset es "Xmaxima Manual (xmaxima browser)" "Xmaxima - manual (navegador Xmaxima)"
mcset es "Maxima Manual (web browser)" "Maxima - manual (navegador Web)"
mcset es "Xmaxima Manual (web browser)" "Xmaxima - manual (navegador Web)"
mcset es "Maxima Homepage" "Página Web de Maxima"
mcset es "Project Page" "Página del proyecto"
mcset es "Bug Reports" "Reporte de bugs"


### EHref.tcl
mcset es "args to href.  Wanted 1, got:" "args to href. Wanted 1, got:"


### EMaxima.tcl
mcset es "unable to call" "incapaz de invocar a"

### EOpenplot.tcl
mcset es "not allowed, only" "no permitido, únicamente"


### Bindings.tcl
mcset es "
Bindings:
<Return>    This sends the current expression (ie where the insert
cursor is)  for evaluation.
<Linefeed>  (Control-j) This inserts a newline, and is useful
for entering multiline input.
<Control-k> Kills the current line and puts it in kill ring.
Successive control-k's append their output together.
<Control-y> Yank out the last kill, Meta-y cycles through previous
kills.
<Control-g> Interrupts the current computation.
<Alt-p>     Gets the previous input in the history of inputs; if the
first input is reached, it proceeds to the last input. If
some characters are written before clicking on Alt-p, only
history items containing those characters will be considered.
<Alt-n>     Gets the next input in the history of inputs; if the end is
reached, it proceeds to the first input. If some characters
are written before clicking on Alt-n, only history items
containing those characters will be considered.
<Alt-s>     Print again the Maxima input prompt.
" "
Atajos:
<Return>  Esto envia la expresión actual (ie es decir donde
se encuentra el cursor) para ser evaluada.
<Linefeed> (Control-j) Inserta una nueva línea, lo cual es muy útil
para el ingreso de entradas multilíneas.
<Control-k> Elimina la línea actual y la coloca en la papelera.
Control-K's sucesivos borrarán las líneas posteriores, incluyendo salidas.
<Control-y> Yank out the last kill, Meta-y cycles thru previous
kills.
<Control-g> Interrumpe el computo actual.
<Alt-p> Accede a la entrada previa en la historia de entradas de la
sesión; si se llega al comienzo, continuará en la última entrada.
Si se escriben algunos caracteres antes de oprimir Alt-p, serán
consideradas únicamente las entradas que contengan esos caractéres.
<Alt-n> Accede a la próxima entrada en la historia de entradas de la
sesión; si se llega al final, continuará en la primera entrada.
Si se escriben algunos caracteres antes de oprimir Alt-n, serán
consideradas únicamente las entradas que contengan esos caractéres.
<Alt-s> Introduce nuevamente el indicador de entrada de datos de
Maxima.
"


### Browser.tcl
mcset es "illegal command in rich text:" "comando ilegal en texto enriquecido"
mcset es "unable to evaluate command:" "incapaz de evaluar el comando:"
mcset es "History List" "Historial"
mcset es "This window may be dragged elsewhere by grabbing this title bar with the mouse.  Double clicking on a history item, moves to that page." "Esta ventana puede ser arrastrada a otra parte agarrando esta barra de título con el mouse. Haciendo doble click en uno de los items del historial, llevará a dicha página."
mcset es "Close" "Cerrar"
mcset es "Remove the history list" "Remover del historial"
mcset es "unknown type:" "tipo desconocido:"
mcset es "error unsupported url type:" "error: url de tipo desconocido"
mcset es "Error connecting to %s on %s\n%s" "Error conectándose a %s en %s\n%s"
mcset es "not supported" "no soportado"
mcset es "need version of tk with 'binary' command for images" "se necesita la versión de tk con el comando 'binary' para imágenes"
mcset es "could not get image" "no se puede obtener la imagen"
mcset es "unknown type of image" "tipo de imagen desconocido"
mcset es "cant remove tmp file" "no se puede remover el archivo temporal"
mcset es "Unable to open an image for" "incapaz de abrir una image por"
mcset es "Opening" "Abriendo"
mcset es "unable to evaluate" "incapaz de evaluar"
mcset es "Font Settings\nThe proportional font is " "Configuración de Fuentes\nLa fuente proporcional es "
mcset es "with a size adjustment of " "con un tamaño de "
mcset es "\nThe fixed font is " "\n La fuente fijada es "
mcset es "Default nmtp servers  " "Servidores nmtp por defecto "
mcset es "http Proxy host and port:" "Servidor proxy y puerto"
mcset es "\nIf you are behind a firewall enter the name of your http proxy host and port,\n eg: `foo.ma.utexas.edu 3128', otherwise leave this blank" "\nSi tu equipo está detrás de una firewall ingresa el nombre y el puerto del servidor proxy, \n eg: `foo.ma.utexas.edu 3128', de otra manera deja este espacio en blanco."
mcset es "\nShould plot windows be " "\nDesplegar las ventanas de graficación " 
mcset es "embedded" "embebida"
mcset es "separate" "separada"
mcset es "multiple" "multiple"
mcset es " Apply and Quit " "Aplicar y salir"
mcset es " Apply " "Aplicar"
mcset es " Cancel " "Cancelar"
mcset es " Save Preferences " "Guardar preferencias"


### Getdata1.tcl
mcset es "error:" "error:"
mcset es "writing" "escribiendo"


### Myhtml.tcl
mcset es "Internal font error:" "Erro interno de fuente"
mcset es "bad window" "ventana errada"
mcset es "not yet" "no aún"
mcset es "Click to follow link to" "Haz click en el siguente vínculo"
mcset es " Enter search keywords: " "Ingresa las palabras a buscar"
mcset es "cant decode hex" "no se puede decodificar hex"


### OpenMath.tcl
mcset es "Back" "Atrás"
mcset es "Forward" "Siguiente"
mcset es "Edit" "Editar"
mcset es "Bring down a menu with some edit options" "Despliega un menu con algunas opciones para edición"
mcset es "show edit bar" "mostrar barra de edición"
mcset es "Mark the currently selected region of the text window, so that clicking on the region will cause evaluation by a program specified below." "Marca la región seleccionada actualmente en la ventana de texto, así que dando click en esta región causará la evaluación por el programa especificado más abajo."
mcset es "mark for eval" "marcar para evaluar"
mcset es "Set `%s' to be the current type used by 'mark for eval' for making the selected region sensitive to double clicking." "Establece '%s' como el programa que evaluará las regiones marcadas para evaluación, es decir aquellas que son sensibles al doble click."
mcset es "Options" "Opciones"
mcset es "File" "Archivo"
mcset es "Offer possible help options, including toggling \n	whether to show balloon help messages" "Ofrece posibles opciones de ayuda, incluyendo mostrar o ocultar el globo de mensajes de ayuda."
mcset es "Hide Balloon Help" "Ocultar globo de ayuda"
mcset es "Show Balloon Help" "Mostrar globo de ayuda"
mcset es {Menu of file options, for saving and preferences} {Menu para opciones de archivo, para guardar y preferencias}
mcset es "Reload" "Recargar"
mcset es "Interrupt" "Interrumpir"
mcset es {Try to interrupt the current remote computations.} {Intenta interrumpir el computo remoto actual.}
mcset es "Abort" "Abortar"
mcset es {Try to abort the current remote computation.} {Intenta abortar el computo remoto actual.}
mcset es "Stop" "Parar"
mcset es {Stop reading the current url or image.} {Para la lectura de la url o imagen actual.}
mcset es "Forget" "Eliminar"
mcset es {Move back one in the history, and remove the current one from the history, unless it was the first window.} {Se desplaza sobre el historial de archivos y remueve el archivo actual, a menos que sea el único archivo abierto.}
mcset es "History" "Historial"
mcset es {Display the history list, so that one may be selected by clicking.} \
         {Muestra el historial, y así puedes dar click para seleccionar el archivo.}
mcset es "Base Program" "Programa base"
mcset es {Show and allow altering of the base program, which shows which is the default host for programs to run on.   May also be specified in <body baseprogram= ...> in the .html file.} \
         {Muestra y altera el programa base, el cual muestra cual es el servidor por defecto para la ejecución de programas. También puede ser especificado mediante la etiqueta <body baseprogram=....> en el archivo html.} 
mcset es "Save to file" "Guardar a un archivo"
mcset es "Fonts" "Fuentes"
mcset es {set the default font sizes and types} {Configura los tipos y tamaños de fuente por defecto}
mcset es "Exit" "Salir"
mcset es {Exit this program} {Salir de este programa}
mcset es {Fetch the URL or FILE indicated in the entry box. \
				   A local file is something like file:/home/wfs/foo.om, and a URL \
				   begins with http.} \
{Abre la URL o archivo indicado en la caja de texto. \
				   Un archivo local es algo como file:/home/wfs/foo.om, y una URL \
				   comienza con http.}

mcset es {Address of the current document.  You may modify it and type Enter, to fetch a new document.} \
         {La dirección del documento actual. Puedes modificarla y presionar enter, para abrir un nuevo documento.}
mcset es "Could not open file %s\n%s" "No se puede abrir el archivo %s\n%s"
mcset es "wrote" "escrito"
mcset es "Double clicking (with the left mouse button), in the marked region will cause evaluation. " \
         "Haciendo doble click (con el botón izquierdo del mouse), en la región marcada causará su evaluación"
mcset es "No result field with" "Ningún resultado con"
mcset es "Failed to eval region" "Falla al evaluar la región"
mcset es "Reload the current URL displayed in the window." "Recarga la URL actual mostrada en la ventana"
mcset es " by %s." " por %s"
mcset es " The result will be inserted." "El resultado será insertado."
mcset es " The result field is named" "El resultado esta nombrado"


### Proxy.tcl
mcset es "Could not connect" "No me puedo conectar"


### Wmenu.tcl
mcset es "needs a window name arg" "se necesita un nombre de ventana como arg"
mcset es "error" "error"
mcset es "must be one of:" "debe ser uno de:"
mcset es "This is a menu window" "Esta es una ventana de menu"


### Tryembed.tcl
mcset es "unknown host:" "equipo desconocido"
mcset es "connection from %s and %s disallowed" "conección desde %s y %s rechazada"
mcset es "bad port:" "puerto inválido"
mcset es "wrong args: socket host port OR socket -server command port" \
	 "argumentos inválidos: socket equipo puerto o socket -servidor comando puerto"
mcset es "Cannot change" "No se puede cambiar"
mcset es "unknown option" "opción desconocida"


### Tkmaxima.tcl
mcset es "Usage: xmaxima \[options\] \[url\]" "Uso: xmaxima \[opciones\] \[url\]"
mcset es "           If given, \[url\] will be opened in the help browser instead" "           Si se pasa como argumento, \[url\] debería ser abierta en el navegador de ayuda en cambio de"
mcset es "           of the default starting page." "           la página de inicio por defecto."
mcset es "options:" "opciones"
mcset es "    --help: Display this usage message." "    --help: Muestra este mensaje de uso."
mcset es "    -l <lisp>, --lisp=<lisp>: Use lisp implementation <lisp>." "    -l <lisp>, --lisp=<lisp>: Usa la implementación lisp indicada por <lisp>."
mcset es "    --use-version=<version>: Launch maxima version <version>." "    --use-version=<version>: Ejecuta la versión de maxima indicada por <version>."
mcset es "Error: arguments %s not understood." "Error: argumentos %s no entendidos"
mcset es "Error sourcing %s\n%s" "Error en la fuente %s\n%s"
mcset es "Error starting Maxima:" "Error iniciando Maxima:"


### Send-some.tcl
mcset es "connection closed" "conección cerrada"
mcset es "sending" "enviando"
mcset es "on" "sobre"
mcset es "had error in" "se tuvo un error en"
mcset es "connecting to" "conectandóse a"
mcset es "connected to" "conectado a"
mcset es "Sending scoket interrupt" "Enviando el socket de interrupción"
mcset es "connecting" "conectando"
mcset es "Can't connect to" "No me puedo conectar a"
mcset es "You can try another host by altering Base Program under the \"File\" menu." \
         "Puedes intentar con otro equipo alterando el programa base por medio del menu \"Archivo\". "
	 

### RunMaxima.tcl	 
mcset es "Could not start Maxima - empty command" "No se puede iniciar Maxima - comando vacío"
mcset es "Can't execute" "No puedo ejecutar"
mcset es "Could not open a socket " "No se pudo abrir el socket"
mcset es "Closed socket" "Socket cerrado"
mcset es "Killed process" "Proceso terminado"
mcset es "Starting Maxima" "Iniciando Maxima"
mcset es "Starting maxima timed out.  Wait longer?" "La inicialización de maxima excedió el tiempo permitido. Esperar más tiempo?"
mcset es "Starting Maxima timed out" "la inicialización de Maxima excedió el tiempo permitido"
mcset es "Failed to start Maxima" "Falló la ejecución de Maxima"
mcset es "Started Maxima" "Maxima se ha inicializado"
mcset es "Error sending to Maxima:" "Error enviando a Maxima:"
mcset es "You must Restart" "Debes reiniciar"
mcset es "You may need to Restart" "Puede que sea necesario reiniciar"
mcset es "socket closed" "socket cerrado"
mcset es "timed out" "tiempo excedido"
mcset es "Sending signal %s to process %s" "Enviando la señal %s al proceso %s"
