/* Original version of this file copyright 1999 by Michael Wester,
 * and retrieved from http://www.math.unm.edu/~wester/demos/MathvsCS/local.macsyma
 * circa 2006-10-23.
 *
 * Released under the terms of the GNU General Public License, version 2,
 * per message dated 2007-06-03 from Michael Wester to Robert Dodier
 * (contained in the file wester-gpl-permission-message.txt).
 *
 * See: "A Critique of the Mathematical Abilities of CA Systems"
 * by Michael Wester, pp 25--60 in
 * "Computer Algebra Systems: A Practical Guide", edited by Michael J. Wester
 * and published by John Wiley and Sons, Chichester, United Kingdom, 1999.
 */
/* ----------[ M a c s y m a ]---------- */
/* ---------- Initialization ---------- */
showtime: all$
prederror: false$
/* ---------- Mathematics vs Computer Science ---------- */
/* Is k really treated as a local variable in the following situations where it
   is clearly a mathematically local variable? */
sum(k, k, 1, 4);
product(k, k, 1, 3);
limit(k, k, 0);
integrate(k, k, 0, 1);
k: 1$
sum(k, k, 1, 4);
product(k, k, 1, 3);
errcatch(limit(k, k, 0));
errcatch(integrate(k, k, 0, 1));
/* ---------- Quit ---------- */
quit();
