
(IN-PACKAGE "COMMON-LISP-USER") 
(PROCLAIM '(FTYPE (FUNCTION (T T T T) T) MAXIMA::OUTPUT-POINTS-TCL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) *) MAXIMA::XMAXIMA-PALLETES
            MAXIMA::XMAXIMA-PALETTE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) T) MAXIMA::XMAXIMA-COLOR
            MAXIMA::XMAXIMA-COLORS)) 
(PROCLAIM '(FTYPE (FUNCTION (T T) *) MAXIMA::XMAXIMA-CURVE-STYLE)) 
(PROCLAIM '(FTYPE (FUNCTION (T T) T) MAXIMA::XMAXIMA-PRINT-HEADER)) 