linel: 65$

kill (all)$

'(if a > b then c else d);

'if a > b then c else d;

'(if a > b then c);

'if a > b then c;

'(if a then if b then if c then d else if e then f else g else if h then i else j else k);

'if a then 'if b then 'if c then d else 'if e then f else g else 'if h then i else j else k;

'(if a then b);

'(if a then b else d);

'(if a then b elseif c then false);

'(if a then b elseif c then d);

'(if a then b elseif c then d else f);

'(if a then b elseif c then d elseif e then false);

'(if a then b elseif c then d elseif e then f);

'(if a then b elseif c then d elseif e then f else h);

'(if a then b elseif c then d elseif e then f elseif g then false);

'(if a then b elseif c then d elseif e then f elseif g then h);

'if a then b;

'if a then b else d;

'if a then b elseif c then false;

'if a then b elseif c then d;

'if a then b elseif c then d else f;

'if a then b elseif c then d elseif e then false;

'if a then b elseif c then d elseif e then f;

'if a then b elseif c then d elseif e then f else h;

'if a then b elseif c then d elseif e then f elseif g then false;

'if a then b elseif c then d elseif e then f elseif g then h;

(a: z^3,
b: q/p,
c: x < 1024,
d: 1729.0,
e: 'if a > b then c else d,
f: 'if c < d then a elseif c < b then e else g,
g: abs(r),
h: %pi*e,
0);

'if a then b;

'if a then b else d;

'if a then b elseif c then false;

'if a then b elseif c then d;

'if a then b elseif c then d else f;

'if a then b elseif c then d elseif e then false;

'if a then b elseif c then d elseif e then f;

'if a then b elseif c then d elseif e then f else h;

'if a then b elseif c then d elseif e then f elseif g then false;

'if a then b elseif c then d elseif e then f elseif g then h;
