/* not found
(kill(all),example("/"));
done; */

(kill(all),example(additive));
done;

(kill(all),example(algsys));
done;

(kill(all),example(allroots));
done;

(kill(all),example(antisymmetric));
done;

(kill(all),example(append));
done;

(kill(all),example(arrayinfo));
done;

(kill(all),example(arrays));
done;

(kill(all),example(at));
done;

(kill(all),example(atvalue));
done;

(kill(all),example(augcoefmatrix));
done;

(kill(all),example(bezout));
done;

/* not found
(kill(all),example(block));
done; */

/* not found
(kill(all),example(bothcoeff));
done; */

(kill(all),example(catch));
done;

(kill(all),example(cf));
done;

(kill(all),example(cfdisrep));
done;

(kill(all),example(cfexpand));
done;

/* user input required - asks if a > 0
(kill(all),example(changevar));
done; */

(kill(all),example(charpoly));
done;

(kill(all),example(coeff));
done;

(kill(all),example(combine));
done;

(kill(all),example(commutative));
done;

(kill(all),example(complex));
done;

(kill(all),example(content));
done;

(kill(all),example(defmatch));
done;

(kill(all),example(deftaylor));
done;

(kill(all),example(delete));
done;

(kill(all),example(depends));
done;

(kill(all),example(derivdegree));
done;

(kill(all),example(desolve));
done;

(kill(all),example(diff));
done;

(kill(all),example(display));
done;

(kill(all),example(divide));
done;

/* something bad happens
(kill(all),example(do));
done; */

(kill(all),example(dotscrules));
done;

(kill(all),example(dpart));
done;

(kill(all),example(echelon));
done;

(kill(all),example(eliminate));
done;

/* user input required
(kill(all),example(entermatrix));
done; */

(kill(all),example(equations));
done;

(kill(all),example(ev));
done;

(kill(all),example(evaluation));
done;

(kill(all),example(evenfun));
done;

(kill(all),example(exp));
done;

(kill(all),example(expand));
done;

(kill(all),example(factcomb));
done;

(kill(all),example(factor));
done;

(kill(all),example(factorsum));
done;

(kill(all),example(featurep));
done;

(kill(all),example(freeof));
done;

(kill(all),example(fullmap));
done;

(kill(all),example(fullmapl));
done;

(kill(all),example(funcsolve));
done;

(kill(all),example(functions));
done;

(kill(all),example(genmatrix));
done;

(kill(all),example(get));
done;

(kill(all),example(gfactor));
done;

(kill(all),example(gradef));
done;

(kill(all),example(horner));
done;

/* something bad happens
(kill(all),example(if));
done; */

/* user input required
(kill(all),example(ilt));
done; */

(kill(all),example(inpart));
done;

(kill(all),example(integrate));
done;

(kill(all),example(is));
done;

(kill(all),example(isolate));
done;

/* not found
(kill(all),example(lambda));
done; */

(kill(all),example(laplace));
done;

(kill(all),example(lassociative));
done;

(kill(all),example(let));
done;

(kill(all),example(letrules));
done;

(kill(all),example(limit));
done;

(kill(all),example(linear));
done;

(kill(all),example(linsolve));
done;

(kill(all),example(listofvars));
done;

(kill(all),example(lists));
done;

(kill(all),example(logcontract));
done;

(kill(all),example(map));
done;

(kill(all),example(matchdeclare));
done;

(kill(all),example(matrices));
done;

(kill(all),example(minfactorial));
done;

(kill(all),example(multiplicative));
done;

(kill(all),example(multthru));
done;

(kill(all),example(nary));
done;

(kill(all),example(nounify));
done;

(kill(all),example(nroots));
done;

(kill(all),example(numfactor));
done;

(kill(all),example(nusum));
done;

(kill(all),example(oddfun));
done;

(kill(all),example(ode2));
done;

(kill(all),example(optimize));
done;

(kill(all),example(ordergreat));
done;

(kill(all),example(orderless));
done;

(kill(all),example(outative));
done;

(kill(all),example(part));
done;

(kill(all),example(partfrac));
done;

(kill(all),example(partition));
done;

(kill(all),example(pickapart));
done;

(kill(all),example(poissimp));
done;

(kill(all),example(polarform));
done;

(kill(all),example(poly_discriminant));
done;

(kill(all),example(posfun));
done;

(kill(all),example(powerseries));
done;

(kill(all),example(printprops));
done;

(kill(all),example(product));
done;

(kill(all),example(properties));
done;

(kill(all),example(propvars));
done;

(kill(all),example(qunit));
done;

(kill(all),example(radcan));
done;

(kill(all),example(rank));
done;

(kill(all),example(rassociative));
done;

/* not found
(kill(all),example(ratcoeff));
done; */

(kill(all),example(ratdiff));
done;

(kill(all),example(ratexpand));
done;

(kill(all),example(ratsimp));
done;

(kill(all),example(ratsubst));
done;

(kill(all),example(ratweight));
done;

(kill(all),example(realpart));
done;

(kill(all),example(realroots));
done;

(kill(all),example(residue));
done;

(kill(all),example(resultant));
done;

(kill(all),example(reveal));
done;

(kill(all),example(reverse));
done;

(kill(all),example(risch));
done;

(kill(all),example(rootscontract));
done;

(kill(all),example(scanmap));
done;

(kill(all),example(scsimp));
done;

(kill(all),example(solve));
done;

(kill(all),example(specint));
done;

(kill(all),example(sqfr));
done;

/* requires input
(kill(all),example(subst));
done; */

(kill(all),example(substinpart));
done;

(kill(all),example(substpart));
done;

(kill(all),example(sum));
done;

(kill(all),example(symmetric));
done;

(kill(all),example(syntax));
done;

(kill(all),example(taylor));
done;

(kill(all),example(taytorat));
done;

(kill(all),example(tellrat));
done;

(kill(all),example(tellsimp));
done;

(kill(all),example(triangularize));
done;

(kill(all),example(trig));
done;

(kill(all),example(trigexpand));
done;

(kill(all),example(trigreduce));
done;

(kill(all),example(unorder));
done;

(kill(all),example(xthru));
done;

(kill(all),example(zeroequiv));
done;

