//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace mixpanel.detail {

class MixpanelSDKPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="SWIGRegisterExceptionCallbacks_MixpanelSDK")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="SWIGRegisterExceptionCallbacks_MixpanelSDK")]
  #endif
    public static extern void SWIGRegisterExceptionCallbacks_MixpanelSDK(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate,
                                ExceptionDelegate indexOutOfRangeDelegate,
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate,
                                ExceptionDelegate overflowDelegate,
                                ExceptionDelegate systemExceptionDelegate);

    #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_MixpanelSDK")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_MixpanelSDK")]
  #endif
    public static extern void SWIGRegisterExceptionArgumentCallbacks_MixpanelSDK(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

      [AOT.MonoPInvokeCallback (typeof (ExceptionArgumentDelegate))]
    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionArgumentDelegate))]
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionArgumentDelegate))]
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_MixpanelSDK(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionArgumentCallbacks_MixpanelSDK(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      }
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(MixpanelSDKPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(MixpanelSDKPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="SWIGRegisterStringCallback_MixpanelSDK")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="SWIGRegisterStringCallback_MixpanelSDK")]
  #endif
    public static extern void SWIGRegisterStringCallback_MixpanelSDK(SWIGStringDelegate stringDelegate);

      [AOT.MonoPInvokeCallback (typeof (SWIGStringDelegate))]
    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_MixpanelSDK(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static MixpanelSDKPINVOKE() {
  }


  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_new_Value__SWIG_0")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_new_Value__SWIG_0")]
  #endif
  public static extern global::System.IntPtr CSharp_new_Value__SWIG_0();

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_new_Value__SWIG_1")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_new_Value__SWIG_1")]
  #endif
  public static extern global::System.IntPtr CSharp_new_Value__SWIG_1(int jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_new_Value__SWIG_2")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_new_Value__SWIG_2")]
  #endif
  public static extern global::System.IntPtr CSharp_new_Value__SWIG_2(double jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_new_Value__SWIG_3")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_new_Value__SWIG_3")]
  #endif
  public static extern global::System.IntPtr CSharp_new_Value__SWIG_3(float jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_new_Value__SWIG_4")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_new_Value__SWIG_4")]
  #endif
  public static extern global::System.IntPtr CSharp_new_Value__SWIG_4(string jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_new_Value__SWIG_5")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_new_Value__SWIG_5")]
  #endif
  public static extern global::System.IntPtr CSharp_new_Value__SWIG_5(bool jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_new_Value__SWIG_6")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_new_Value__SWIG_6")]
  #endif
  public static extern global::System.IntPtr CSharp_new_Value__SWIG_6(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_delete_Value")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_delete_Value")]
  #endif
  public static extern void CSharp_delete_Value(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_get__SWIG_0")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_get__SWIG_0")]
  #endif
  public static extern global::System.IntPtr CSharp_Value_get__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_isValidIndex")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_isValidIndex")]
  #endif
  public static extern bool CSharp_Value_isValidIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_append")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_append")]
  #endif
  public static extern global::System.IntPtr CSharp_Value_append(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_get__SWIG_1")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_get__SWIG_1")]
  #endif
  public static extern global::System.IntPtr CSharp_Value_get__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_removeMember")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_removeMember")]
  #endif
  public static extern global::System.IntPtr CSharp_Value_removeMember(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_isMember")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_isMember")]
  #endif
  public static extern bool CSharp_Value_isMember(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_toStyledString")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_toStyledString")]
  #endif
  public static extern string CSharp_Value_toStyledString(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_asString")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_asString")]
  #endif
  public static extern string CSharp_Value_asString(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_asInt")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_asInt")]
  #endif
  public static extern int CSharp_Value_asInt(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_asFloat")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_asFloat")]
  #endif
  public static extern float CSharp_Value_asFloat(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_asDouble")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_asDouble")]
  #endif
  public static extern double CSharp_Value_asDouble(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_asBool")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_asBool")]
  #endif
  public static extern bool CSharp_Value_asBool(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_isNull")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_isNull")]
  #endif
  public static extern bool CSharp_Value_isNull(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_isBool")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_isBool")]
  #endif
  public static extern bool CSharp_Value_isBool(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_isInt")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_isInt")]
  #endif
  public static extern bool CSharp_Value_isInt(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_isIntegral")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_isIntegral")]
  #endif
  public static extern bool CSharp_Value_isIntegral(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_isDouble")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_isDouble")]
  #endif
  public static extern bool CSharp_Value_isDouble(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_isNumeric")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_isNumeric")]
  #endif
  public static extern bool CSharp_Value_isNumeric(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_isString")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_isString")]
  #endif
  public static extern bool CSharp_Value_isString(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_isArray")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_isArray")]
  #endif
  public static extern bool CSharp_Value_isArray(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_isObject")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_isObject")]
  #endif
  public static extern bool CSharp_Value_isObject(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_size")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_size")]
  #endif
  public static extern uint CSharp_Value_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_empty")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_empty")]
  #endif
  public static extern bool CSharp_Value_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_clear")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_clear")]
  #endif
  public static extern void CSharp_Value_clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_resize")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_resize")]
  #endif
  public static extern void CSharp_Value_resize(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_at__SWIG_0")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_at__SWIG_0")]
  #endif
  public static extern global::System.IntPtr CSharp_Value_at__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_at__SWIG_1")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_at__SWIG_1")]
  #endif
  public static extern global::System.IntPtr CSharp_Value_at__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_set__SWIG_0")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_set__SWIG_0")]
  #endif
  public static extern void CSharp_Value_set__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_set__SWIG_1")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_set__SWIG_1")]
  #endif
  public static extern void CSharp_Value_set__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_set__SWIG_2")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_set__SWIG_2")]
  #endif
  public static extern void CSharp_Value_set__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_set__SWIG_3")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_set__SWIG_3")]
  #endif
  public static extern void CSharp_Value_set__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Value_set__SWIG_4")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Value_set__SWIG_4")]
  #endif
  public static extern void CSharp_Value_set__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_new_Mixpanel__SWIG_0")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_new_Mixpanel__SWIG_0")]
  #endif
  public static extern global::System.IntPtr CSharp_new_Mixpanel__SWIG_0(string jarg1, bool jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_new_Mixpanel__SWIG_1")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_new_Mixpanel__SWIG_1")]
  #endif
  public static extern global::System.IntPtr CSharp_new_Mixpanel__SWIG_1(string jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_new_Mixpanel__SWIG_2")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_new_Mixpanel__SWIG_2")]
  #endif
  public static extern global::System.IntPtr CSharp_new_Mixpanel__SWIG_2(string jarg1, string jarg2, string jarg3, bool jarg4);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_new_Mixpanel__SWIG_3")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_new_Mixpanel__SWIG_3")]
  #endif
  public static extern global::System.IntPtr CSharp_new_Mixpanel__SWIG_3(string jarg1, string jarg2, string jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_delete_Mixpanel")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_delete_Mixpanel")]
  #endif
  public static extern void CSharp_delete_Mixpanel(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_identify")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_identify")]
  #endif
  public static extern void CSharp_Mixpanel_identify(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_alias")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_alias")]
  #endif
  public static extern void CSharp_Mixpanel_alias(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_register_")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_register_")]
  #endif
  public static extern void CSharp_Mixpanel_register_(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_register_properties")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_register_properties")]
  #endif
  public static extern void CSharp_Mixpanel_register_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_register_once")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_register_once")]
  #endif
  public static extern bool CSharp_Mixpanel_register_once(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_register_once_properties")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_register_once_properties")]
  #endif
  public static extern bool CSharp_Mixpanel_register_once_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_unregister")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_unregister")]
  #endif
  public static extern bool CSharp_Mixpanel_unregister(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_unregister_properties")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_unregister_properties")]
  #endif
  public static extern bool CSharp_Mixpanel_unregister_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_get_super_properties")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_get_super_properties")]
  #endif
  public static extern global::System.IntPtr CSharp_Mixpanel_get_super_properties(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_clear_super_properties")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_clear_super_properties")]
  #endif
  public static extern void CSharp_Mixpanel_clear_super_properties(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_start_timed_event")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_start_timed_event")]
  #endif
  public static extern bool CSharp_Mixpanel_start_timed_event(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_start_timed_event_once")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_start_timed_event_once")]
  #endif
  public static extern bool CSharp_Mixpanel_start_timed_event_once(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_clear_timed_event")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_clear_timed_event")]
  #endif
  public static extern bool CSharp_Mixpanel_clear_timed_event(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_clear_timed_events")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_clear_timed_events")]
  #endif
  public static extern void CSharp_Mixpanel_clear_timed_events(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_reset")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_reset")]
  #endif
  public static extern void CSharp_Mixpanel_reset(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_track__SWIG_0")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_track__SWIG_0")]
  #endif
  public static extern void CSharp_Mixpanel_track__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_track__SWIG_1")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_track__SWIG_1")]
  #endif
  public static extern void CSharp_Mixpanel_track__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_set")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_set")]
  #endif
  public static extern void CSharp_Mixpanel_People_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_set_properties")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_set_properties")]
  #endif
  public static extern void CSharp_Mixpanel_People_set_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_set_once")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_set_once")]
  #endif
  public static extern void CSharp_Mixpanel_People_set_once(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_set_once_properties")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_set_once_properties")]
  #endif
  public static extern void CSharp_Mixpanel_People_set_once_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_unset")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_unset")]
  #endif
  public static extern void CSharp_Mixpanel_People_unset(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_unset_properties")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_unset_properties")]
  #endif
  public static extern void CSharp_Mixpanel_People_unset_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_increment")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_increment")]
  #endif
  public static extern void CSharp_Mixpanel_People_increment(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_increment_properties")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_increment_properties")]
  #endif
  public static extern void CSharp_Mixpanel_People_increment_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_append")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_append")]
  #endif
  public static extern void CSharp_Mixpanel_People_append(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_append_properties")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_append_properties")]
  #endif
  public static extern void CSharp_Mixpanel_People_append_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_union_")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_union_")]
  #endif
  public static extern void CSharp_Mixpanel_People_union_(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_union_properties")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_union_properties")]
  #endif
  public static extern void CSharp_Mixpanel_People_union_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_track_charge__SWIG_0")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_track_charge__SWIG_0")]
  #endif
  public static extern void CSharp_Mixpanel_People_track_charge__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_track_charge__SWIG_1")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_track_charge__SWIG_1")]
  #endif
  public static extern void CSharp_Mixpanel_People_track_charge__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_clear_charges")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_clear_charges")]
  #endif
  public static extern void CSharp_Mixpanel_People_clear_charges(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_set_push_id")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_set_push_id")]
  #endif
  public static extern void CSharp_Mixpanel_People_set_push_id(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_set_first_name")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_set_first_name")]
  #endif
  public static extern void CSharp_Mixpanel_People_set_first_name(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_set_last_name")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_set_last_name")]
  #endif
  public static extern void CSharp_Mixpanel_People_set_last_name(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_set_name")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_set_name")]
  #endif
  public static extern void CSharp_Mixpanel_People_set_name(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_set_email")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_set_email")]
  #endif
  public static extern void CSharp_Mixpanel_People_set_email(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_People_set_phone")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_People_set_phone")]
  #endif
  public static extern void CSharp_Mixpanel_People_set_phone(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_delete_Mixpanel_People")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_delete_Mixpanel_People")]
  #endif
  public static extern void CSharp_delete_Mixpanel_People(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_people_set")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_people_set")]
  #endif
  public static extern void CSharp_Mixpanel_people_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_people_get")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_people_get")]
  #endif
  public static extern global::System.IntPtr CSharp_Mixpanel_people_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_LogEntry_level_set")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_LogEntry_level_set")]
  #endif
  public static extern void CSharp_Mixpanel_LogEntry_level_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_LogEntry_level_get")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_LogEntry_level_get")]
  #endif
  public static extern int CSharp_Mixpanel_LogEntry_level_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_LogEntry_message_set")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_LogEntry_message_set")]
  #endif
  public static extern void CSharp_Mixpanel_LogEntry_message_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_LogEntry_message_get")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_LogEntry_message_get")]
  #endif
  public static extern string CSharp_Mixpanel_LogEntry_message_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_new_Mixpanel_LogEntry")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_new_Mixpanel_LogEntry")]
  #endif
  public static extern global::System.IntPtr CSharp_new_Mixpanel_LogEntry();

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_delete_Mixpanel_LogEntry")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_delete_Mixpanel_LogEntry")]
  #endif
  public static extern void CSharp_delete_Mixpanel_LogEntry(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_set_minimum_log_level")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_set_minimum_log_level")]
  #endif
  public static extern void CSharp_Mixpanel_set_minimum_log_level(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_get_next_log_entry")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_get_next_log_entry")]
  #endif
  public static extern bool CSharp_Mixpanel_get_next_log_entry(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_utc_now")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_utc_now")]
  #endif
  public static extern string CSharp_Mixpanel_utc_now();

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_on_reachability_changed")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_on_reachability_changed")]
  #endif
  public static extern void CSharp_Mixpanel_on_reachability_changed(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_set_maximum_queue_size")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_set_maximum_queue_size")]
  #endif
  public static extern void CSharp_Mixpanel_set_maximum_queue_size(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_set_flush_interval")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_set_flush_interval")]
  #endif
  public static extern void CSharp_Mixpanel_set_flush_interval(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_flush_queue")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_flush_queue")]
  #endif
  public static extern void CSharp_Mixpanel_flush_queue(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_Mixpanel_director_connect")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_Mixpanel_director_connect")]
  #endif
  public static extern void CSharp_Mixpanel_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
