//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace mixpanel.detail {

class MixpanelSDKPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="SWIGRegisterExceptionCallbacks_MixpanelSDK")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="SWIGRegisterExceptionCallbacks_MixpanelSDK")]
  #endif
    public static extern void SWIGRegisterExceptionCallbacks_MixpanelSDK(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate,
                                ExceptionDelegate indexOutOfRangeDelegate,
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate,
                                ExceptionDelegate overflowDelegate,
                                ExceptionDelegate systemExceptionDelegate);

    #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_MixpanelSDK")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_MixpanelSDK")]
  #endif
    public static extern void SWIGRegisterExceptionArgumentCallbacks_MixpanelSDK(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

      [AOT.MonoPInvokeCallback (typeof (ExceptionArgumentDelegate))]
    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionArgumentDelegate))]
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionArgumentDelegate))]
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_MixpanelSDK(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionArgumentCallbacks_MixpanelSDK(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      }
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(MixpanelSDKPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(MixpanelSDKPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="SWIGRegisterStringCallback_MixpanelSDK")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="SWIGRegisterStringCallback_MixpanelSDK")]
  #endif
    public static extern void SWIGRegisterStringCallback_MixpanelSDK(SWIGStringDelegate stringDelegate);

      [AOT.MonoPInvokeCallback (typeof (SWIGStringDelegate))]
    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_MixpanelSDK(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static MixpanelSDKPINVOKE() {
  }


  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_new_Value__SWIG_0___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_new_Value__SWIG_0___")]
  #endif
  public static extern global::System.IntPtr new_Value__SWIG_0();

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_new_Value__SWIG_1___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_new_Value__SWIG_1___")]
  #endif
  public static extern global::System.IntPtr new_Value__SWIG_1(int jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_new_Value__SWIG_2___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_new_Value__SWIG_2___")]
  #endif
  public static extern global::System.IntPtr new_Value__SWIG_2(double jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_new_Value__SWIG_3___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_new_Value__SWIG_3___")]
  #endif
  public static extern global::System.IntPtr new_Value__SWIG_3(float jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_new_Value__SWIG_4___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_new_Value__SWIG_4___")]
  #endif
  public static extern global::System.IntPtr new_Value__SWIG_4(string jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_new_Value__SWIG_5___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_new_Value__SWIG_5___")]
  #endif
  public static extern global::System.IntPtr new_Value__SWIG_5(bool jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_new_Value__SWIG_6___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_new_Value__SWIG_6___")]
  #endif
  public static extern global::System.IntPtr new_Value__SWIG_6(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_delete_Value___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_delete_Value___")]
  #endif
  public static extern void delete_Value(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_get__SWIG_0___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_get__SWIG_0___")]
  #endif
  public static extern global::System.IntPtr Value_get__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_isValidIndex___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_isValidIndex___")]
  #endif
  public static extern bool Value_isValidIndex(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_append___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_append___")]
  #endif
  public static extern global::System.IntPtr Value_append(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_get__SWIG_1___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_get__SWIG_1___")]
  #endif
  public static extern global::System.IntPtr Value_get__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_removeMember___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_removeMember___")]
  #endif
  public static extern global::System.IntPtr Value_removeMember(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_isMember___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_isMember___")]
  #endif
  public static extern bool Value_isMember(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_toStyledString___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_toStyledString___")]
  #endif
  public static extern string Value_toStyledString(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_asString___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_asString___")]
  #endif
  public static extern string Value_asString(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_asInt___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_asInt___")]
  #endif
  public static extern int Value_asInt(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_asFloat___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_asFloat___")]
  #endif
  public static extern float Value_asFloat(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_asDouble___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_asDouble___")]
  #endif
  public static extern double Value_asDouble(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_asBool___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_asBool___")]
  #endif
  public static extern bool Value_asBool(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_isNull___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_isNull___")]
  #endif
  public static extern bool Value_isNull(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_isBool___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_isBool___")]
  #endif
  public static extern bool Value_isBool(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_isInt___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_isInt___")]
  #endif
  public static extern bool Value_isInt(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_isIntegral___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_isIntegral___")]
  #endif
  public static extern bool Value_isIntegral(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_isDouble___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_isDouble___")]
  #endif
  public static extern bool Value_isDouble(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_isNumeric___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_isNumeric___")]
  #endif
  public static extern bool Value_isNumeric(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_isString___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_isString___")]
  #endif
  public static extern bool Value_isString(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_isArray___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_isArray___")]
  #endif
  public static extern bool Value_isArray(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_isObject___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_isObject___")]
  #endif
  public static extern bool Value_isObject(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_size___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_size___")]
  #endif
  public static extern uint Value_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_empty___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_empty___")]
  #endif
  public static extern bool Value_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_clear___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_clear___")]
  #endif
  public static extern void Value_clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_resize___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_resize___")]
  #endif
  public static extern void Value_resize(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_at__SWIG_0___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_at__SWIG_0___")]
  #endif
  public static extern global::System.IntPtr Value_at__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_at__SWIG_1___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_at__SWIG_1___")]
  #endif
  public static extern global::System.IntPtr Value_at__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_set__SWIG_0___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_set__SWIG_0___")]
  #endif
  public static extern void Value_set__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_set__SWIG_1___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_set__SWIG_1___")]
  #endif
  public static extern void Value_set__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_set__SWIG_2___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_set__SWIG_2___")]
  #endif
  public static extern void Value_set__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_set__SWIG_3___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_set__SWIG_3___")]
  #endif
  public static extern void Value_set__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Value_set__SWIG_4___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Value_set__SWIG_4___")]
  #endif
  public static extern void Value_set__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_new_Mixpanel__SWIG_0___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_new_Mixpanel__SWIG_0___")]
  #endif
  public static extern global::System.IntPtr new_Mixpanel__SWIG_0(string jarg1, bool jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_new_Mixpanel__SWIG_1___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_new_Mixpanel__SWIG_1___")]
  #endif
  public static extern global::System.IntPtr new_Mixpanel__SWIG_1(string jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_new_Mixpanel__SWIG_2___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_new_Mixpanel__SWIG_2___")]
  #endif
  public static extern global::System.IntPtr new_Mixpanel__SWIG_2(string jarg1, string jarg2, string jarg3, bool jarg4);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_new_Mixpanel__SWIG_3___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_new_Mixpanel__SWIG_3___")]
  #endif
  public static extern global::System.IntPtr new_Mixpanel__SWIG_3(string jarg1, string jarg2, string jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_delete_Mixpanel___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_delete_Mixpanel___")]
  #endif
  public static extern void delete_Mixpanel(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_identify___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_identify___")]
  #endif
  public static extern void Mixpanel_identify(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_alias___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_alias___")]
  #endif
  public static extern void Mixpanel_alias(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_register____")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_register____")]
  #endif
  public static extern void Mixpanel_register_(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_register_properties___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_register_properties___")]
  #endif
  public static extern void Mixpanel_register_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_register_once___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_register_once___")]
  #endif
  public static extern bool Mixpanel_register_once(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_register_once_properties___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_register_once_properties___")]
  #endif
  public static extern bool Mixpanel_register_once_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_unregister___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_unregister___")]
  #endif
  public static extern bool Mixpanel_unregister(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_unregister_properties___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_unregister_properties___")]
  #endif
  public static extern bool Mixpanel_unregister_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_get_super_properties___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_get_super_properties___")]
  #endif
  public static extern global::System.IntPtr Mixpanel_get_super_properties(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_clear_super_properties___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_clear_super_properties___")]
  #endif
  public static extern void Mixpanel_clear_super_properties(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_start_timed_event___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_start_timed_event___")]
  #endif
  public static extern bool Mixpanel_start_timed_event(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_start_timed_event_once___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_start_timed_event_once___")]
  #endif
  public static extern bool Mixpanel_start_timed_event_once(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_clear_timed_event___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_clear_timed_event___")]
  #endif
  public static extern bool Mixpanel_clear_timed_event(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_clear_timed_events___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_clear_timed_events___")]
  #endif
  public static extern void Mixpanel_clear_timed_events(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_reset___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_reset___")]
  #endif
  public static extern void Mixpanel_reset(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_track__SWIG_0___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_track__SWIG_0___")]
  #endif
  public static extern void Mixpanel_track__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_track__SWIG_1___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_track__SWIG_1___")]
  #endif
  public static extern void Mixpanel_track__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_has_tracked_integration___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_has_tracked_integration___")]
  #endif
  public static extern bool Mixpanel_has_tracked_integration(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_set_tracked_integration___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_set_tracked_integration___")]
  #endif
  public static extern void Mixpanel_set_tracked_integration(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set___")]
  #endif
  public static extern void Mixpanel_People_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_properties___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_properties___")]
  #endif
  public static extern void Mixpanel_People_set_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_once___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_once___")]
  #endif
  public static extern void Mixpanel_People_set_once(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_once_properties___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_once_properties___")]
  #endif
  public static extern void Mixpanel_People_set_once_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_unset___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_unset___")]
  #endif
  public static extern void Mixpanel_People_unset(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_unset_properties___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_unset_properties___")]
  #endif
  public static extern void Mixpanel_People_unset_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_increment___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_increment___")]
  #endif
  public static extern void Mixpanel_People_increment(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_increment_properties___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_increment_properties___")]
  #endif
  public static extern void Mixpanel_People_increment_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_append___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_append___")]
  #endif
  public static extern void Mixpanel_People_append(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_append_properties___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_append_properties___")]
  #endif
  public static extern void Mixpanel_People_append_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_union____")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_union____")]
  #endif
  public static extern void Mixpanel_People_union_(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_union_properties___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_union_properties___")]
  #endif
  public static extern void Mixpanel_People_union_properties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_track_charge__SWIG_0___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_track_charge__SWIG_0___")]
  #endif
  public static extern void Mixpanel_People_track_charge__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_track_charge__SWIG_1___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_track_charge__SWIG_1___")]
  #endif
  public static extern void Mixpanel_People_track_charge__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_clear_charges___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_clear_charges___")]
  #endif
  public static extern void Mixpanel_People_clear_charges(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_push_id___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_push_id___")]
  #endif
  public static extern void Mixpanel_People_set_push_id(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_first_name___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_first_name___")]
  #endif
  public static extern void Mixpanel_People_set_first_name(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_last_name___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_last_name___")]
  #endif
  public static extern void Mixpanel_People_set_last_name(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_name___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_name___")]
  #endif
  public static extern void Mixpanel_People_set_name(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_email___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_email___")]
  #endif
  public static extern void Mixpanel_People_set_email(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_phone___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_People_set_phone___")]
  #endif
  public static extern void Mixpanel_People_set_phone(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_delete_Mixpanel_People___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_delete_Mixpanel_People___")]
  #endif
  public static extern void delete_Mixpanel_People(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_people_set___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_people_set___")]
  #endif
  public static extern void Mixpanel_people_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_people_get___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_people_get___")]
  #endif
  public static extern global::System.IntPtr Mixpanel_people_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_LogEntry_level_set___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_LogEntry_level_set___")]
  #endif
  public static extern void Mixpanel_LogEntry_level_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_LogEntry_level_get___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_LogEntry_level_get___")]
  #endif
  public static extern int Mixpanel_LogEntry_level_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_LogEntry_message_set___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_LogEntry_message_set___")]
  #endif
  public static extern void Mixpanel_LogEntry_message_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_LogEntry_message_get___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_LogEntry_message_get___")]
  #endif
  public static extern string Mixpanel_LogEntry_message_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_new_Mixpanel_LogEntry___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_new_Mixpanel_LogEntry___")]
  #endif
  public static extern global::System.IntPtr new_Mixpanel_LogEntry();

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_delete_Mixpanel_LogEntry___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_delete_Mixpanel_LogEntry___")]
  #endif
  public static extern void delete_Mixpanel_LogEntry(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_set_minimum_log_level___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_set_minimum_log_level___")]
  #endif
  public static extern void Mixpanel_set_minimum_log_level(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_get_next_log_entry___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_get_next_log_entry___")]
  #endif
  public static extern bool Mixpanel_get_next_log_entry(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_utc_now___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_utc_now___")]
  #endif
  public static extern string Mixpanel_utc_now();

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_on_reachability_changed___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_on_reachability_changed___")]
  #endif
  public static extern void Mixpanel_on_reachability_changed(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_set_maximum_queue_size___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_set_maximum_queue_size___")]
  #endif
  public static extern void Mixpanel_set_maximum_queue_size(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_set_flush_interval___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_set_flush_interval___")]
  #endif
  public static extern void Mixpanel_set_flush_interval(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_flush_queue___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_flush_queue___")]
  #endif
  public static extern void Mixpanel_flush_queue(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_director_connect___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("MixpanelSDK", EntryPoint="CSharp_mixpanelfdetail_Mixpanel_director_connect___")]
  #endif
  public static extern void Mixpanel_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
