(kill(all), load(odelin),display2d : false, 0);
0$

odelin(y+'diff(y,x,2),y,x);
set(%e^-(%i*x),%e^(%i*x))$

odelin('diff(y,x)+'diff(y,x,2),y,x);
set(1,%e^-x)$

(assume(notequal(b,a)), odelin(a*b*y+(-b-a+1)*x*'diff(y,x)+x^2*'diff(y,x,2),y,x));
set(x^a,x^b)$

(forget(notequal(b,a)),0);
0$

odelin(2*y+9*x^2*'diff(y,x)+9*x^2*'diff(y,x,2),y,x);
set(bessel_j(1/6,-%i*x/2)*sqrt(-x)*%e^-(x/2),bessel_y(1/6,-%i*x/2)*sqrt(-x)*%e^-(x/2))$

odelin(-y+3*(x-1)*'diff(y,x)+2*x*(x-1)*'diff(y,x,2),y,x);
set((x-1)/sqrt(x), (log(sqrt(x)+1)*x-log(sqrt(x)-1)*x-2*sqrt(x)-log(sqrt(x)+1) +log(sqrt(x)-1)) /sqrt(x))$

odelin(x^2*y+x*'diff(y,x)+x^2*'diff(y,x,2),y,x);
set(bessel_j(0,-x),bessel_y(0,-x))$

odelin(-4*y+'diff(y,x)+x*'diff(y,x,2),y,x);
set(bessel_j(0,4*sqrt(-x)), bessel_y(0,4*sqrt(-x)))$

odelin(y+(x+x^2)*'diff(y,x)+x^2*'diff(y,x,2),y,x);
set(kummer_m(%i,2*%i+1,-x)*x^%i,kummer_u(%i,2*%i+1,-x)*x^%i)$

odelin(-y+(2-x)*'diff(y,x)+3*x*'diff(y,x,2),y,x);
set(x^(1/3)*%e^(x/3),gamma_incomplete(-1/3,x/3)*x^(1/3)*%e^(x/3))$

odelin(-(3+x)*y+2*x^2*'diff(y,x)+4*x^2*'diff(y,x,2),y,x);
set((x-2)/sqrt(x),%e^-(x/2)/sqrt(x))$

odelin(y+(x^2-x)*'diff(y,x)+x^2*'diff(y,x,2),y,x); /* 13 */
set(x*%e^-x,gamma_incomplete(0,-x)*x*%e^-x)$

odelin(-x*y-'diff(y,x)+x*'diff(y,x,2),y,x);
set(bessel_j(1,-%i*x)*x,bessel_y(1,-%i*x)*x)$

odelin((x-2)*y+8*x*'diff(y,x)+3*x^2*'diff(y,x,2),y,x);
set(bessel_j(-7/3,2*sqrt(x)/sqrt(3))/x^(5/6), bessel_y(-7/3,2*sqrt(x)/sqrt(3))/x^(5/6))$

odelin(-2*y+(x-1)*'diff(y,x)+x*'diff(y,x,2),y,x);
set(x^2,gamma_incomplete(-2,x)*x^2)$

odelin(-4*y+(5+x)*'diff(y,x)+x*(1+x)*'diff(y,x,2),y,x);
set(gauss_a(-6,-2,-3,-x)/x^4,gauss_b(-6,-2,-3,-x)/x^4)$

odelin(-y+(1-x)*'diff(y,x)+x*'diff(y,x,2),y,x);
set(%e^x,gamma_incomplete(0,x)*%e^x)$

odelin(y-x*(x+1)*'diff(y,x)+x^2*'diff(y,x,2),y,x);
set(x*%e^x,gamma_incomplete(0,x)*x*%e^x)$

odelin(-4*y+2*(1-x)*'diff(y,x)+3*x*'diff(y,x,2),y,x);
set(kummer_m(-1,4/3,-2*x/3)*x^(1/3)*%e^(2*x/3),kummer_u(-1,4/3,-2*x/3)*x^(1/3)*%e^(2*x/3))$

odelin(-y+(2+x)*'diff(y,x)+x*'diff(y,x,2),y,x);
set(kummer_m(-2,0,-x)/x,kummer_u(-2,0,-x)/x)$

odelin(-2*y+(1/2-4*x)*'diff(y,x)+x*(1-x)*'diff(y,x,2),y,x); /* 22 */
set(sqrt(x)/(x-1)^(5/2), (2*sqrt(x-1)*x-3*log(sqrt(x)+sqrt(x-1))*sqrt(x) +3*log(sqrt(x-1)-sqrt(x))*sqrt(x)+4*sqrt(x-1)) /(x-1)^(5/2))$

odelin(-45*y+(1-27*x)*'diff(y,x)+3*x*(1-x)*'diff(y,x,2),y,x);
set(gauss_a(-4,-2,5/3,x)*x^(2/3)/(x-1)^(23/3),gauss_b(-4,-2,5/3,x)*x^(2/3)/(x-1)^(23/3))$

odelin(-2*y+(1-6*x)*'diff(y,x)+2*x*(1-x)*'diff(y,x,2),y,x);
set((log(sqrt(x)+sqrt(x-1))*sqrt(x)-log(sqrt(x-1)-sqrt(x))*sqrt(x) -2*sqrt(x-1)) /(x-1)^(3/2),sqrt(x)/(x-1)^(3/2))$

odelin(-6*y+(3-10*x)*'diff(y,x)+2*x*(1-x)*'diff(y,x,2),y,x);
set(1/((x-1)^(5/2)*sqrt(x)), (4*sqrt(x-1)*x^(3/2)-10*sqrt(x-1)*sqrt(x)+3*log(sqrt(x)+sqrt(x-1)) -3*log(sqrt(x-1)-sqrt(x))) /((x-1)^(5/2)*sqrt(x)))$

odelin(-y+(1-3*x)*'diff(y,x)+x*(1-x)*'diff(y,x,2),y,x);
set(1/(x-1),log(x)/(x-1))$

odelin((-y)/4+(2-2*x)*'diff(y,x)+x*(1-x)*'diff(y,x,2),y,x);
set(gauss_a(-1/2,-1/2,0,x)/x,gauss_b(-1/2,-1/2,0,x)/x)$


odelin((4*x^2-1)*y+4*x*'diff(y,x)+4*x^2*'diff(y,x,2),y,x);
set(%e^-(%i*x)/sqrt(x),%e^(%i*x)/sqrt(x))$

odelin((9*x^2-16)*y+9*x*'diff(y,x)+9*x^2*'diff(y,x,2),y,x);
set(bessel_j(-4/3,-x),bessel_y(-4/3,-x))$

odelin((x^2-1)*y+x*'diff(y,x)+x^2*'diff(y,x,2),y,x);
set(bessel_j(1,-x),bessel_y(1,-x))$

odelin(x^2*y+x*'diff(y,x)+x^2*'diff(y,x,2),y,x);
set(bessel_j(0,-x), bessel_y(0,-x))$

odelin((9*x^2-4)*y+9*x*'diff(y,x)+9*x^2*'diff(y,x,2),y,x);
set(bessel_j(-2/3,-x), bessel_y(-2/3,-x))$

odelin((x^2-16)*y+x*'diff(y,x)+x^2*'diff(y,x,2),y,x);
set(bessel_j(4,-x), bessel_y(4,-x))$

odelin((x^2-1)*y+x*'diff(y,x)+x^2*'diff(y,x,2),y,x);
set(bessel_j(1,-x), bessel_y(1,-x))$

odelin((x^2-4)*y+x*'diff(y,x)+x^2*'diff(y,x,2),y,x);
set(bessel_j(2,-x), bessel_y(2,-x))$

odelin(6*y+5*'diff(y,x)+'diff(y,x,2),y,x);
set(%e^-(3*x),%e^-(2*x))$

odelin(16*y+8*'diff(y,x)+'diff(y,x,2),y,x);
set(%e^-(4*x),x*%e^-(4*x))$

odelin(-y+'diff(y,x)+'diff(y,x,2),y,x);
set(%e^(-sqrt(5)*x/2-x/2),%e^(sqrt(5)*x/2-x/2))$

odelin(-4*y+7*'diff(y,x)+2*'diff(y,x,2),y,x);
set(%e^-(4*x),%e^(x/2))$

odelin(-11*y-'diff(y,x)+'diff(y,x,2),y,x);
set(%e^(x/2-3*sqrt(5)*x/2),%e^(3*sqrt(5)*x/2+x/2))$

odelin(25*y+20*'diff(y,x)+4*'diff(y,x,2),y,x);
set(%e^-(5*x/2),x*%e^-(5*x/2))$

odelin(7*y-8*'diff(y,x)+'diff(y,x,2),y,x);
set(%e^x,%e^(7*x))$

odelin(8*y+4*'diff(y,x)+'diff(y,x,2),y,x);
set(%e^(-2*%i*x-2*x),%e^(2*%i*x-2*x))$

odelin(25*y+10*'diff(y,x)+'diff(y,x,2),y,x);
set(%e^-(5*x),x*%e^-(5*x))$

odelin(7*y+'diff(y,x,2),y,x);
set(%e^-(sqrt(7)*%i*x),%e^(sqrt(7)*%i*x))$

odelin(5*y+2*'diff(y,x)+'diff(y,x,2),y,x);
set(%e^(-2*%i*x-x),%e^(2*%i*x-x))$

odelin(26*y-2*'diff(y,x)+'diff(y,x,2),y,x);
set(%e^(x-5*%i*x),%e^(5*%i*x+x))$

odelin(6*y+6*x*'diff(y,x)+x^2*'diff(y,x,2),y,x);
set(1/x^3,1/x^2)$

odelin(15*y+13*x*'diff(y,x)+2*x^2*'diff(y,x,2),y,x);
set(1/x^3,1/x^(5/2))$

odelin(17*y-x*'diff(y,x)+x^2*'diff(y,x,2),y,x);
set(x^(1-4*%i),x^(4*%i+1))$

odelin(-3*y+2*'diff(y,x)+x^2*'diff(y,x,2),y,x);
set(kummer_m((sqrt(13)+3)/2,sqrt(13)+1,-2/x) *(x)^(-sqrt(13)/2-1/2)*%e^(2/x)*abs(x), kummer_u((sqrt(13)+3)/2,
    sqrt(13)+1,-2/x) *(x)^(-sqrt(13)/2-1/2)*%e^(2/x)*abs(x))$

odelin(-(3+x)*y+2*x^2*'diff(y,x)+4*x^2*'diff(y,x,2),y,x);
set((x-2)/sqrt(x),%e^-(x/2)/sqrt(x))$

odelin(y+(x^2-x)*'diff(y,x)+x^2*'diff(y,x,2),y,x);
set(x*%e^-x,gamma_incomplete(0,-x)*x*%e^-x)$

odelin(-x*y-'diff(y,x)+x*'diff(y,x,2),y,x);
set(bessel_j(1,-%i*x)*x, bessel_y(1,-%i*x)*x)$

odelin((x-2)*y+8*x*'diff(y,x)+3*x^2*'diff(y,x,2),y,x);
set(bessel_j(-7/3,2*sqrt(x)/sqrt(3))/x^(5/6), bessel_y(-7/3,2*sqrt(x)/sqrt(3))/x^(5/6))$

odelin(-2*y+(x-1)*'diff(y,x)+x*'diff(y,x,2),y,x);
set(x^2,gamma_incomplete(-2,x)*x^2)$

odelin(-4*y+(5+x)*'diff(y,x)+x*(1+x)*'diff(y,x,2),y,x);
set(gauss_a(-6,-2,-3,-x)/x^4,gauss_b(-6,-2,-3,-x)/x^4)$

odelin(-y+(1-x)*'diff(y,x)+x*'diff(y,x,2),y,x);
set(%e^x,gamma_incomplete(0,x)*%e^x)$

odelin(y-x*(x+1)*'diff(y,x)+x^2*'diff(y,x,2),y,x);
set(x*%e^x,gamma_incomplete(0,x)*x*%e^x)$

odelin(-y+2*(1-x)*'diff(y,x)+3*x*'diff(y,x,2),y,x);
set(kummer_m(1/2,4/3,-2*x/3)*x^(1/3)*%e^(2*x/3),
        kummer_u(1/2,4/3,-2*x/3)*x^(1/3)*%e^(2*x/3))$

(assume((2*n-b)*(2*n+b) > 0),0);
0$

odelin((b^2-(4*n^2-1))*y/(4*x^2)+'diff(y,x,2),y,x);
set(x^(1/2-sqrt(2*n-b)*sqrt(2*n+b)/2),x^(sqrt(2*n-b)*sqrt(2*n+b)/2+1/2))$

(forget((2*n-b)*(2*n+b) > 0),0);
0$

odelin(((a^2-n^2)/x^2+b^2)*y+(1-2*a)*'diff(y,x)/x+'diff(y,x,2),y,x);
set(bessel_j(n,-b*x)*x^a, bessel_y(n,-b*x)*x^a)$

odelin(b^2*x^3*y+'diff(y,x,2),y,x);
set(bessel_j(-1/5,2*abs(b)*x^(5/2)/5)*sqrt(x), bessel_y(-1/5,2*abs(b)*x^(5/2)/5)*sqrt(x))$

odelin(b^2*x^2*y+'diff(y,x,2),y,x);
set(bessel_j(-1/4,-b*x^2/2)*abs(x)/sqrt(-x), bessel_y(-1/4,-b*x^2/2)*abs(x)/sqrt(-x))$ 

odelin(4*(x^2-n^2/x^2)*y+'diff(y,x)/x+'diff(y,x,2),y,x);
set(bessel_j(n,x^2)*abs(x)/x,bessel_y(n,x^2)*abs(x)/x)$

odelin((1-n^2/x)*y/(4*x)+'diff(y,x)/x+'diff(y,x,2),y,x);
set(bessel_j(n,sqrt(x)), bessel_y(n,sqrt(x)))$

odelin(y/(4*x)+(1-n)*'diff(y,x)/x+'diff(y,x,2),y,x);
set(bessel_j(n,sqrt(x))*x^(n/2), bessel_y(n,sqrt(x))*x^(n/2))$


odelin(('diff(y,x,1) = (-((-96*x^3-200*x^5-100*x^7)*y
                    +(x+4*x^3+6*x^5+4*x^7+x^9)*'diff(y,x,2)))
                    /(-1-2*x^2+2*x^6+x^8)),y,x);
set(-bessel_j(5,-1/(x^2+1)),-bessel_y(5,-1/(x^2+1)))$


odelin(('diff(y,x,2) = (-((x+3*x^3+3*x^5+x^7)*y
                    +(1-7*x^2+14*x^4-10*x^6+x^8+x^10)*'diff(y,x,1)))
                    /(x-3*x^3+2*x^5+2*x^7-3*x^9+x^11)),y,x);
set(bessel_j(0,-x/(x^2-1)), bessel_y(0,-x/(x^2-1)))$

odelin(('diff(y,x,2) = (-((-x+3*x^3-3*x^5+x^7)*y
                    +(-1-5*x-16*x^2-31*x^3-43*x^4-40*x^5-25*x^6-7*x^7+2*x^8
                        +3*x^9+x^10)
                     *'diff(y,x,1)))
                    /(-x-4*x^2-9*x^3-12*x^4-9*x^5+9*x^7+12*x^8+9*x^9+4*x^10
                        +x^11)),y,x);
set(bessel_j(0,-x/(x^2+x+1)), bessel_y(0,-x/(x^2+x+1)))$

odelin(('diff(y,x,2) = (2*x*'diff(y,x,1)-2*y)/x^2),y,x);
set(x,x^2)$

odelin(('diff(y,x,2) = (-((-4+5*x-x^2)*y+(4*x-5*x^2+x^3)*'diff(y,x,1)))/(x^3-2*x^2)),y,x);
set(x,(x-1)*x*%e^-x)$

odelin(('diff(y,x,2) = ((1+4*x-8*x^2+4*x^3-x^4)*y
                    +(-x-4*x^2+8*x^3-4*x^4+x^5)*'diff(y,x,1))
                    /(-1+x-4*x^2+2*x^3-3*x^4+x^5)),y,x);
set(x,%e^x/(x^2+1))$

odelin(('diff(y,x,2) = ((-6+2*b+(24-a-8*b)*x+(-26+6*a+8*b)*x^2+(16-12*a)*x^3 +(8*a-8)*x^4) *y
      +((4-b)*x+(4*b-15)*x^2+(15-4*b)*x^3-8*x^4+4*x^5) *'diff(y,x,1)) /(x^2-3*x^3+2*x^4)),y,x);
set(kummer_m(a,b,(x-1)*x)*x^2,kummer_u(a,b,(x-1)*x)*x^2)$


odelin(('diff(y,x,2) = ((-a^2+6*a^2*x-12*a^2*x^2+8*a^2*x^3)*y +(-1+(4-3*a)*x+
        (7*a-4)*x^2-8*a*x^3+4*a*x^4)*'diff(y,x,1)) /(a*x-3*a*x^2+2*a*x^3)),y,x);

set(kummer_m(a,1/a,(x-1)*x),kummer_u(a,1/a,(x-1)*x))$

odelin(('diff(y,x,2) = ((a+6*a*x+12*a*x^2+8*a*x^3)*y
                    +(-1+2*a+(12*a-11)*x+(30*a-27)*x^2+(44*a-38)*x^3
                        +(42*a-34)*x^4+(24*a-18)*x^5+(8*a-6)*x^6)
                     *'diff(y,x,1))
                    /(1+5*x+12*x^2+19*x^3+20*x^4+15*x^5+7*x^6+2*x^7)),y,x);
set(bessel_j(-((2*a-1)/2),-(%i/(2*(x^2+x+1))))*(x^2+x+1)^(a-1/2) *%e^(1/(2*x^2+2*x+2)),
  bessel_y(-((2*a-1)/2),-(%i/(2*(x^2+x+1))))*(x^2+x+1)^(a-1/2) *%e^(1/(2*x^2+2*x+2)))$

odelin(('diff(y,x,2) = (-(n*u*y+((1+n+u)*x-k)*'diff(y,x,1)))/(x^2-x)),y,x);
set(gauss_a(n,u,k,x),gauss_b(n,u,k,x))$

odelin(('diff(y,x,2) = (-(n*u*y+(-15+3*k-15*n-15*u+(1+n+u)*x)*'diff(y,x,1))) /(180-27*x+x^2)),y,x);
set(gauss_a(n,u,u+n-k+1,(x-12)/3),gauss_b(n,u,u+n-k+1,(x-12)/3))$

odelin(('diff(y,x,2) = (-((-n*u+(-1+n+u)*x+(1-k)*x^2+x^3)*y 
     +((-1+n+u)*x-k*x^2+2*x^3)*'diff(y,x,1)))/(x^3-x^2)),y,x);
set(gauss_a(n-k+1,n,-u+n+1,x)*x^n*%e^-x,
        gauss_b(n-k+1,n,-u+n+1,x)*x^n*%e^-x)$


odelin(('diff(y,x,2) = (-((-304+115*x-60*x^2+9*x^3)*y
                    +(96*x-69*x^2+18*x^3)*'diff(y,x,1)))
                    /(9*x^3-9*x^2)),y,x)$
set(x^(19/3)*%e^-x,
  x^(16/3)*%e^-x *(60*x^5*log(x)-240*x^4*log(x)+360*x^3*log(x)-240*x^2*log(x) +60*x*log(x)
    -60*x^5*log(x-1)+240*x^4*log(x-1) -360*x^3*log(x-1)+240*x^2*log(x-1)-60*x*log(x-1)
    -60*x^4+210*x^3-260*x^2+125*x-12) /(x-1)^4)$

odelin(('diff(y,x,2) = (-((-30+180*x-360*x^2+240*x^3)*y
                    +(-7+14*x+32*x^2-92*x^3+46*x^4)*'diff(y,x,1)))
                    /(-x+2*x^2+2*x^3-5*x^4+2*x^5)),y,x);
set(1/((x-1)^6*x^6), (60*x^8*log(x^2-x-1)-240*x^7*log(x^2-x-1)+120*x^6*log(x^2-x-1)
    +480*x^5*log(x^2-x-1)-300*x^4*log(x^2-x-1) -480*x^3*log(x^2-x-1)+120*x^2*log(x^2-x-1)
    +240*x*log(x^2-x-1)+60*log(x^2-x-1)+12*x^10-60*x^9+72*x^8 +72*x^7-276*x^6+324*x^5+60*x^4
    -456*x^3+4*x^2+248*x+77) /((x-1)^6*x^6*(x^2-x-1)^4))$
  
odelin(('diff(y,x,2) = (30*y+(15-20*x+5*x^2)*'diff(y,x,1))/(-2+5*x-4*x^2+x^3)),y,x);
set((x-1)^6, (x-1)^5*(60*x^5*log(x-1)-540*x^4*log(x-1)+1920*x^3*log(x-1)-3360*x^2*log(x-1)
    +2880*x*log(x-1)-960*log(x-1)-60*x^5*log(x-2) +540*x^4*log(x-2)-1920*x^3*log(x-2)
    +3360*x^2*log(x-2) -2880*x*log(x-2)+960*log(x-2)-60*x^4+450*x^3-1250*x^2 +1515*x-667) /(x-2)^4)$

odelin(('diff(y,x,2) = (-((a^2+a*b)*y+(-8-2*a-b+(1+2*a+b)*x)*'diff(y,x,1)))
                    /(2-3*x+x^2)),y,x)$
set(gauss_a(a,b+a,7,x-1),gauss_b(a,b+a,7,x-1))$


odelin(('diff(y,x,2) = (-((a^2+6*a^2*x+12*a^2*x^2+8*a^2*x^3)*y
                    +(1+a+(3+6*a)*x+(5+14*a)*x^2+(4+16*a)*x^3+(2+8*a)*x^4)
                     *'diff(y,x,1)))
                    /(x+4*x^2+6*x^3+5*x^4+2*x^5)),y,x);
set(1/(x^a*(x+1)^a), ('integrate(x^(a-1)*(x+1)^(a-1)*(2*x+1)/(x^2+x+1)^a,x))/(x^a*(x+1)^a))$ 

odelin(('diff(y,x,2) = (-((2*x^2-1)*y+8*x*'diff(y,x,1)))/(2*x^2-2)),y,x);
set(spherodialwave_a(1,1/2,1/4,-x),spherodialwave_b(1,1/2,1/4,-x))$


odelin(('diff(y,x,2) = (-((6*x^2-28)*y+(6*x^3+2*x^5)*'diff(y,x,1)))/(x^6-x^4)),y,x);
set(spherodialwave_a(-3,12,7,-(1/x))*x^5*abs(x)/((x-1)^3*(x+1)^3),
  spherodialwave_b(-3,12,7,-(1/x))*x^5*abs(x)/((x-1)^3*(x+1)^3))$

odelin(('diff(y,x,2) = (-((-22-12*x+6*x^2)*y
                    +(-8+28*x-38*x^2+26*x^3-10*x^4+2*x^5)*'diff(y,x,1)))
                    /(-2*x+9*x^2-16*x^3+14*x^4-6*x^5+x^6)),y,x);
set(spherodialwave_a(-3,12,7,-1/(x-1))*(x-1)^6/((x-2)^3*x^3),
  spherodialwave_b(-3,12,7,-1/(x-1))*(x-1)^6/((x-2)^3*x^3))$ 

odelin(('diff(y,x,2) = (-((784-4703*x+9401*x^2-6254*x^3-20*x^4+8*x^5)*y
                    +(-4*x+12*x^2-16*x^3+8*x^4)*'diff(y,x,1)))
                    /(-4*x^2+16*x^3-20*x^4+8*x^5)),y,x);
set(bessel_j(28,sqrt(x-1)*sqrt(x)),bessel_y(28,sqrt(x-1)*sqrt(x)))$
             
odelin(('diff(y,x,2) = (-(2-933156*x)*y-x^2*'diff(y,x,1))/x^3),y,x);
set(bessel_j(1932,2^(3/2)/sqrt(x))*abs(x)/x, bessel_y(1932,2^(3/2)/sqrt(x))*abs(x)/x)$

odelin(('diff(y,x,2) = (-1+x-x^2-4*x^3+x^4-x^5+x^6)*'diff(y,x,1)/(x^6-x^2)),y,x);
set(1,'integrate((x^2+1)*%e^(x-1/x)/(x*(x^2-1)),x))$

odelin(('diff(y,x,2) = ((1+3*x^2+3*x^4+x^6)*y
                    +(-x-x^3-6*x^4+x^5-2*x^6+x^7)*'diff(y,x,1))
                    /(x^7-x^3)),y,x);
set(x/((x-1)*(x+1)),x*%e^(x-1/x)/((x-1)*(x+1)))$               

odelin(('diff(y,x,2) = ((2+6*x^2+6*x^4+2*x^6)*y
                    +(-2*x+3*x^2-2*x^3-6*x^4+2*x^5-x^6+2*x^7)*'diff(y,x,1))
                    /(2*x^7-2*x^3)),y,x);
set(sqrt(x-1)*sqrt(x+1)*%e^(x-1/x)/sqrt(x), sqrt(x-1)*sqrt(x+1)*%e^(x-1/x) *('integrate((x^2+1)*%e^(1/x-x) /(sqrt(x-1)*sqrt(x)*sqrt(x+1)*(x^2-1)),x)) /sqrt(x))$

odelin(('diff(y,x,2) = (-(a^2*y-2*a^2*x*y+6*a*x^2*y-4*x^3*y+a^2*'diff(y,x,1)
                              +4*a^2*x^2*'diff(y,x,1)-8*a*x^3*'diff(y,x,1)
                              +4*x^4*'diff(y,x,1)))
                    /(2*x*(x-a)*(-a+2*x-2*a*x+2*x^2))),y,x);
                
set(%e^-x,%e^-x*'integrate((2*x^2+(2-2*a)*x-a)*%e^x/(sqrt(x)*sqrt(x-a)),x))$

odelin(('diff(y,x,2) = ((-a^2+(-1+a+a*(1+2*a))*x+(-1-a+(-1-a)*a)*x^2)*y
                    +((2*a-1)*x-4*a*x^2+(1+2*a)*x^3)*'diff(y,x,1))
                    /(x^2-2*x^3+x^4)),y,x);
set((x-1)*x^a,(x-1)*x^a*log(x))$                

odelin(2*y-2*x*'diff(y,x,1)+(x^2-1)*'diff(y,x,2),y,x);
set((x-1)^2,x)$


odelin(-y+4*x*'diff(y,x,1)+4*x^2*'diff(y,x,2),y,x);
set(1/sqrt(x),sqrt(x))$

odelin(-15*y+2*'diff(y,x)+'diff(y,x,2),y,x);
set(%e^-(5*x),%e^(3*x))$

odelin(y-(1+x)*'diff(y,x)+x*'diff(y,x,2),y,x);
set(x+1,%e^x)$

odelin((x-1)*y+(1-2*x)*'diff(y,x)+x*'diff(y,x,2),y,x);
set(%e^x,%e^x*log(x))$

odelin(n*y-2*x*'diff(y,x)+'diff(y,x,2),y,x);
set(kummer_m((n+2)/4,1/2,-x^2)*%e^x^2*sqrt(abs(x))/sqrt(-x),
  kummer_u((n+2)/4,1/2,-x^2)*%e^x^2*sqrt(abs(x))/sqrt(-x))$

odelin(n*(1+n)*y-2*x*'diff(y,x)+(1-x^2)*'diff(y,x,2),y,x);
set(gauss_a(-n,n+1,1,-((x-1)/2)),gauss_b(-n,n+1,1,-((x-1)/2)))$

odelin(n*y+(1-x)*'diff(y,x)+x*'diff(y,x,2),y,x);
set(kummer_m(n+1,1,-x)*%e^x,kummer_u(n+1,1,-x)*%e^x)$

(reset(display2d),0);
0$